<?xml version="1.0" encoding="utf-8"?><Database Name="GalTUS2" Class="MSSQL1C81DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVER-SOV2\SQL2005;Initial Catalog=GalTUS2;User ID=sa" SettingsObjectName="Elisy.CfInspector.Properties.Settings" SettingsPropertyName="GalTUS2ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[_YearOffset]" Member="_YearOffsets">
    <Type Name="_YearOffset">
      <Column Name="Offset" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Config" Member="Configs">
    <Type Name="Config">
      <Column Name="FileName" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DataSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BinaryData" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.ConfigSave" Member="ConfigSaves">
    <Type Name="ConfigSave">
      <Column Name="FileName" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DataSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BinaryData" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DBSchema" Member="DBSchemas">
    <Type Name="DBSchema">
      <Column Name="SerializedData" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="FileName" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DataSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BinaryData" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.Params" Member="Params">
    <Type Name="Param">
      <Column Name="FileName" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Creation" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modified" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Attributes" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="DataSize" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BinaryData" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>