//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elisy.MdInternals.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elisy.MdInternals.Resources.StringTemplates", typeof(StringTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {
        ///    26,
        ///    &quot;#ElisyBound:RecordTypeId&quot;,
        ///    &quot;#ElisyBound:RecordValTypeId&quot;,
        ///    &quot;#ElisyBound:ManagerTypeId&quot;,
        ///    &quot;#ElisyBound:ManagerValTypeId&quot;,
        ///    &quot;#ElisyBound:SelectionTypeId&quot;,
        ///    &quot;#ElisyBound:SelectionValTypeId&quot;,
        ///    &quot;#ElisyBound:ListTypeId&quot;,
        ///    &quot;#ElisyBound:ListValTypeId&quot;,
        ///    &quot;#ElisyBound:RecordSetTypeId&quot;,
        ///    &quot;#ElisyBound:RecordSetValTypeId&quot;,
        ///    &quot;#ElisyBound:RecordKeyTypeId&quot;,
        ///    &quot;#ElisyBound:RecordKeyValTypeId&quot;,
        ///    {
        ///      0,
        ///      {
        ///        0,
        ///        {0,0,&quot;#ElisyB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AccumulationRegister {
            get {
                return ResourceManager.GetString("AccumulationRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {
        ///    12,
        ///    {
        ///      0,
        ///      {0,0,&quot;#ElisyBound:Uuid&quot;},
        ///      &quot;#ElisyBound:Name&quot;,
        ///      &quot;#ElisyBound:Synonym&quot;,
        ///      &quot;#ElisyBound:Comment&quot;
        ///    },
        ///    &quot;#ElisyBound:ClientOrdinaryApplication&quot;,
        ///    &quot;#ElisyBound:Server&quot;,
        ///    &quot;#ElisyBound:ExternalConnection&quot;,
        ///    &quot;#ElisyBound:Privileged&quot;,
        ///    &quot;#ElisyBound:Global&quot;,
        ///    &quot;#ElisyBound:ClientManagedApplication&quot;,
        ///    &quot;#ElisyBound:ReturnValuesReuse&quot;,
        ///    &quot;#ElisyBound:ServerCall&quot;
        ///  },
        ///  0
        ///}.
        /// </summary>
        internal static string CommonModule {
            get {
                return ResourceManager.GetString("CommonModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  2,
        ///  {&quot;#ElisyBound:Guid_1_0&quot;},
        ///  6,
        ///  {
        ///    9cd510cd-abfc-11d4-9434-004095e12fc7,
        ///    {
        ///      1,
        ///      {
        ///        36,
        ///        {
        ///          0,
        ///          {
        ///            0,
        ///            {0,0,&quot;#ElisyBound:Uuid&quot;},
        ///            &quot;#ElisyBound:Name&quot;,
        ///            &quot;#ElisyBound:Synonym&quot;,
        ///            &quot;#ElisyBound:Comment&quot;
        ///          }
        ///        },
        ///        &quot;&quot;,
        ///        &quot;#ElisyBound:Int_3_1_1_3&quot;,
        ///        &quot;#ElisyBound:BriefInformation&quot;,
        ///        &quot;#ElisyBound:DetailedInformation&quot;,
        ///        &quot;#ElisyBound:Copy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {
        ///    16,
        ///    &quot;#ElisyBound:Guid_1_1&quot;,
        ///    &quot;#ElisyBound:Guid_1_2&quot;,
        ///    {
        ///      0,
        ///      {
        ///        0,
        ///        {0,0,&quot;#ElisyBound:Uuid&quot;},
        ///        &quot;#ElisyBound:Name&quot;,
        ///        &quot;#ElisyBound:Synonym&quot;,
        ///        &quot;#ElisyBound:Comment&quot;
        ///      }
        ///    },
        ///    &quot;#ElisyBound:Guid_1_4&quot;,
        ///    &quot;#ElisyBound:Int_1_5&quot;,
        ///    &quot;#ElisyBound:Int_1_6&quot;,
        ///    &quot;#ElisyBound:Guid_1_7&quot;,
        ///    &quot;#ElisyBound:Guid_1_8&quot;,
        ///    &quot;#ElisyBound:Guid_1_9&quot;,
        ///    &quot;#ElisyBound:List_1_10&quot;,
        ///    &quot;#ElisyBound:List_1_11&quot;
        ///  },
        ///  5,
        ///  &quot;#El [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataProcessor {
            get {
                return ResourceManager.GetString("DataProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {
        ///    19,
        ///    &quot;#ElisyBound:Guid_1_1&quot;,
        ///    &quot;#ElisyBound:Guid_1_2&quot;,
        ///    &quot;#ElisyBound:Guid_1_3&quot;,
        ///    &quot;#ElisyBound:Guid_1_4&quot;,
        ///    {
        ///      0,
        ///      {
        ///        0,
        ///        {0,0,&quot;#ElisyBound:Uuid&quot;},
        ///        &quot;#ElisyBound:Name&quot;,
        ///        &quot;#ElisyBound:Synonym&quot;,
        ///        &quot;#ElisyBound:Comment&quot;
        ///      }
        ///    },
        ///    &quot;#ElisyBound:Int_1_6&quot;,
        ///    &quot;#ElisyBound:Guid_1_7&quot;,
        ///    &quot;#ElisyBound:Guid_1_8&quot;,
        ///    00000000-0000-0000-0000-000000000000,
        ///    00000000-0000-0000-0000-000000000000,
        ///    2,
        ///    &quot;#Elisy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Enum {
            get {
                return ResourceManager.GetString("Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {&quot;#ElisyBound:Guid_1_0&quot;},
        ///  1,
        ///  {
        ///    c3831ec8-d8d5-4f93-8a22-f9bfae07327f,
        ///    {1,&quot;#ElisyBound:List_3_1_1&quot;,4,&quot;#ElisyBound:List_3_1_3&quot;,&quot;#ElisyBound:List_3_1_4&quot;,&quot;#ElisyBound:Forms&quot;,&quot;#ElisyBound:List_3_1_6&quot;}
        ///  }
        ///}.
        /// </summary>
        internal static string ExternalDataProcessor {
            get {
                return ResourceManager.GetString("ExternalDataProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {&quot;#ElisyBound:Guid_1_0&quot;},
        ///  1,
        ///  {
        ///    e41aff26-25cf-4bb6-b6c1-3f478a75f374,
        ///    {1,&quot;#ElisyBound:List_3_1_1&quot;,4,&quot;#ElisyBound:List_3_1_3&quot;,&quot;#ElisyBound:List_3_1_4&quot;,&quot;#ElisyBound:List_3_1_5&quot;,&quot;#ElisyBound:List_3_1_6&quot;}
        ///  }
        ///}.
        /// </summary>
        internal static string ExternalReport {
            get {
                return ResourceManager.GetString("ExternalReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1,&quot;#ElisyBound:List_1&quot;,0}.
        /// </summary>
        internal static string FunctionalOption {
            get {
                return ResourceManager.GetString("FunctionalOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  1,
        ///  {
        ///    19,
        ///    &quot;#ElisyBound:Guid_1_1&quot;,
        ///    &quot;#ElisyBound:Guid_1_2&quot;,
        ///    {
        ///      0,
        ///      {
        ///        0,
        ///        {0,0,&quot;#ElisyBound:Uuid&quot;},
        ///        &quot;#ElisyBound:Name&quot;,
        ///        &quot;#ElisyBound:Synonym&quot;,
        ///        &quot;#ElisyBound:Comment&quot;
        ///      }
        ///    },
        ///    &quot;#ElisyBound:Guid_1_4&quot;,
        ///    &quot;#ElisyBound:Guid_1_5&quot;,
        ///    00000000-0000-0000-0000-000000000000,
        ///    &quot;#ElisyBound:Int_1_7&quot;,
        ///    &quot;#ElisyBound:Guid_1_8&quot;,
        ///    00000000-0000-0000-0000-000000000000,
        ///    00000000-0000-0000-0000-000000000000,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2,&quot;#ElisyBound:MetadataPackageFileName&quot;,&quot;#ElisyBound:Data0&quot;}.
        /// </summary>
        internal static string RootPointer {
            get {
                return ResourceManager.GetString("RootPointer", resourceCulture);
            }
        }
    }
}
